---
version: "3.8"
services:
  bot:
    build:
      context: "."
      dockerfile: "Dockerfile"
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
      LOG_LEVEL: "${LOG_LEVEL}"
      TEST_SERVERS: "${TEST_SERVERS}"
      DB_CONNECTION_STRING: "${DB_CONNECTION_STRING}"
    deploy:
      restart_policy:
        condition: "unless-stopped"
    network_mode: "host"
    # TODO: only works on Linux
    # NOTE: needed for localhost in DB_CONNECTION_STRING to work
